### ISSUE TITLE
Connection is broken after ~1 min of inactivity

### ISSUE THREAD

**Issue by axenteoctavian** [WalletConnect/WalletConnectSharp#117] opened 2023-09-12 08:20 UTC
The connection is broken after ~1 min of inactivity, and I get some `TaskCanceledExceptions` in console. 
After this, the request is sent to my phone, but the response is not received back.

I am using nuget package version 2.1.0

**Comment by gigajuwels** [comment] 2023-09-12 17:41
Can you provide an example that reproduces the issue? Can you provide the full log you get in the console relating to the `TaskCanceledExceptions` 

> After this, the request is sent to my phone, but the response is not received back.

Do you mean after you get the `TaskCanceledExceptions` in the console, you get the request sent to your phone?

**Comment by axenteoctavian** [comment] 2023-09-12 19:13
> Can you provide an example that reproduces the issue? Can you provide the full log you get in the console relating to the `TaskCanceledExceptions`

I get something like this in the console. 
![image](https://github.com/WalletConnect/WalletConnectSharp/assets/45915201/1c2fda91-3860-4d89-9ecf-a80126a96ba2)

Steps to reproduce the issue:
1. Scan QR and approve the connection
2. Wait >1 min (don't make any requests)
3. Make a request after 1-2 mins
4. Request is received on my phone
5. **Response is not received back**


> Do you mean after you get the `TaskCanceledExceptions` in the console, you get the request sent to your phone?

Yes. I suppose that there are some background tasks canceled or something because of the exceptions and that's why the response is not received.

**Comment by VR-Innovations** [comment] 2023-09-14 15:55
Same issue here, only see the thread has exited logs. Nothing more.

**Comment by gigajuwels** [comment] 2023-09-26 19:56
Closing this as it is a duplicate of #79, let's continue our discussion on that thread.

**Closed as completed by gigajuwels** 2023-09-26 19:56 UTC
Labels: bug, duplicate
