### ISSUE TITLE
after a few minutes the Approval await wont get through 

### ISSUE THREAD

**Issue by VR-Innovations** [WalletConnect/WalletConnectSharp#118] opened 2023-09-15 07:29 UTC
after showing my QR Code:

GenerateQrCode(connectData.Uri);

And awaiting for approval.

SessionData = await connectData.Approval;

I get some exit codes in a few minutes in my debug (VS 2022), I can still the QR code and get the right pop-up in my Trust Wallet screen. But the await connectData.Approval won't hit anymore.

![image](https://github.com/WalletConnect/WalletConnectSharp/assets/114421552/2defb8f8-1a29-40d8-bad3-b002c2c9e22c)

**Comment by VR-Innovations** [comment] 2023-09-15 08:18
Did build 2.1 myself and imported de debugging symbols. Now the output is as next:

The thread 0x7a48 has exited with code 0 (0x0).
The thread 0x60dc has exited with code 0 (0x0).
The thread 0x1c58 has exited with code 0 (0x0).
Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..

Exception thrown: 'System.IO.IOException' in System.Net.Security.dll
Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..

Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..

Exception thrown: 'System.IO.IOException' in System.Private.CoreLib.dll
Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..

Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Net.Http.dll
The operation was canceled.

Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll
The operation was canceled.

Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll
The operation was canceled.

Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll
The operation was canceled.

Exception thrown: 'System.Threading.Tasks.TaskCanceledException' in System.Private.CoreLib.dll
The operation was canceled.

**Comment by gigajuwels** [comment] 2023-09-26 19:57
Closing as this is a duplicate of #79 
Lets move the discussion there

**Closed as completed by gigajuwels** 2023-09-26 19:57 UTC
Labels: duplicate
